name: solution_challenge
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


#---------------------------PACKAGES--------------------------
dependencies:
  youtube_player_flutter: ^8.1.2
  flutter_tts: ^3.6.1
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_storage: ^11.6.5
  firebase_analytics: ^10.0.0
  firebase_messaging: ^14.7.15
  firebase_crashlytics: ^3.4.14
  flutter_dotenv: ^5.1.0
  translator: ^1.0.0
  provider: ^6.0.1
  image_picker: ^1.0.7
  razorpay_flutter: ^1.3.6
  fluttertoast: ^8.2.4

  # Utility Packages
  http: ^1.1.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  intl: ^0.19.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Local assets
  assets:
    - assets/logos/
    - assets/icons/categories/
    - assets/images/onboarding_images/
    - assets/images/banners/
    - assets/images/chatbot/
    - assets/images/login_signup/
    - assets/images/articles/
    - assets/images/education/
    - assets/images/ngo/
    - .env

  #Local fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600