List<String> originalStrings = [
"Explore Your Cycle",
"Access educational resources and valuable content for a healthier menstrual journey.",
"Your Personal Guide",
"Meet Paddy, Your Personal Chatbot Companion - ask questions freely, keep secrets private, and get personalized advice.",
"Empower Change Through Donation and Engagement",
"Support Causes, Share Stories, and Connect with Like-minded Individuals",
'Menstrual Hygiene',
"E-Mail",
"Password",
"Remember me",
"Forgot Password?",
"Sign In",
"Create Account",
"Connect with Period",
"Join our community for personalized menstrual health support and resources.",
"Or Sign In with",
"Skip",
"Enter your email to receive instructions on resetting your password and regain access to Period.",
"Submit",
"Password Reset Email Sent",
"Your account security is our priority! We've sent you a secure link to safely change your password and keep your account protected.",
"Done",
"Resend Email",
"First Name",
"Last Name",
"Username",
"Phone No.",
"Create account",
"or sign up with",
"Verify your email address",
"Confirm your email address to unlock full access to Period's menstrual health resources.",
"Your email has been successfully verified. Enjoy full access to menstrual health resources and community support.",
"Continue",
"Resend Email",
"Type message",
"Categories",
'Organiser',
'Campaigns',
"Events",
"Search Organizations",
'Beginners guide to menstrual health',
'Featured Videos',
'Latest Articles',
'Course Details',
'Introduction',
'What is menopause',
'What do women have discomfort?',
'Change profile picture',
'Profile Information',
'Name',
'Personal Information',
'Date of Birth',
"Account",
'Account Settings',
"Bookmarked Resources",
"My Donations",
"My Blogs",
"Favorite Campaigns",
"Saved Blogs",
"Track your contributions",
"Your experiences at one place",
"Stay connected to causes close to your heart",
"Your favorite reads",
"Explore your saved educational treasures",
'App Settings',
"Change language",
"Tailor your experience with a language switch",
"Welcome to Period!",
"What are periods?",
"Added to liked blogs",
"Failed to add to liked blogs",
"Description",
"No events found",
"Donate now",
"Read more",
"You're In!",
"Thank you for joining the donation event. Your support makes a difference!",
"Register",
"Upload Blog",
"Upload Image",
"Title",
"Content",
"Category",
"Failed to upload blog post",
"Upload Blog",
"Search Blogs",
"Latest Blogs",
"How you doing?",
"Today",
"Feeling Generous,",
"Campaign not found",
"Event not found",
"Search Resources",
"Introduction to Menstrual Health",
"Introduction: What are periods?",
"Impact of Menstrual Health on Daily Life",
"Hey girls! So, let's talk about periods, or as we call it, menstruation! It's a monthly thing that happens to us ladies. Basically, it's when some blood and tissue come out of our uterus through the vagina. It usually kicks in around when you're 12, but hey, it's different for everyone - some may start earlier, some later. But no worries, it's all part of growing up and getting ready for possible baby-making adventures later on! 😊 During this time, you might feel all sorts of emotions and maybe some discomfort, but don't sweat it! There are ways to handle it, and it usually lasts just a few days. It's super important to know about periods so you can take care of yourself and feel comfy chatting about it with trusted adults. 🌸 \n\n Now, let's get into the nitty-gritty! So, periods happen because our bodies are super smart and filled with hormones, which are like little messengers sending signals. The ovaries release two special hormones called estrogen and progesterone. These hormones do this cool thing where they make the lining of our uterus all cozy and thick, like a nice bed for a potential baby. But if there's no baby on the way, that lining breaks down and says bye-bye, causing the bleeding. Then the whole cycle starts over again! It's like a monthly dance party for our bodies! 💃🩸",
"When will i get my first period?",
"FAQs and Common Myths",
"So, most girls usually start getting their first period when they're around 12 years old, but you know what? It's totally cool if it happens any time between 10 and 15. 🎉 Your body's just got its own schedule, doing its thing! There's no set age for it to happen, but there are some hints that it might be on the way: Like, often, about 2 years after your boobs start to grow, you might notice your period showing up. Also, there's this thing called vaginal discharge, which is kind of like mucus, that you might see or feel in your undies. Don't worry, it's all just your body getting ready for this new adventure! 🌟 So, whenever it happens, just roll with it! Your body knows what it's doing. 💪",
'What does the first period feel like?',
"Menstrual Health and Mental Well-being",
"Hey girl! So, when you get your period, it's like your body throwing a little party every month! 🎉 But hey, it's totally normal if you feel a bit funky during this time. Some girls get cramps or feel a bit tired, but don't worry, it's all part of the package. Think of it as your body doing its thing, getting ready for whatever adventures come your way! 💪 And hey, it's not all bad! You might get to rock some cute period undies or try out some fun period products! 🩲 So, embrace the flow, girl! And remember, it's all part of growing up and being awesome! 🌸💖    ",
"Menstrual Hygiene and Management",
"Period Hygiene 101: A Clean Queen's Manual?",
"Hygiene reigns supreme during your period! Start with frequent changes of pads, tampons, or cups – the unsung heroes. 🩸 Wash your hands before and after, making you the hygiene superstar. 🧼 Opt for gentle, fragrance-free wipes or cleansers. 🌸 Keep the sacred 'underwear arsenal' stocked and change as needed. 💪 Embrace the power of showers – they're your period pal. 🚿 Finally, avoid the temptation to flush pads – let the trash be their final destination. 🚫 You're not just maintaining hygiene; you're a clean queen ruling your period domain!",
"Pad Power: Your Period Buddy",
"Pads are like magic shields for your period. 🛡️ Peel one from its wrapper, put it in your undies (sticky side down), and you're set. Swap it every 4-6 hours or sooner if it's full. ⏰ When it's time to part ways, wrap it in toilet paper, toss it in the trash (not the toilet), and ta-da – you're a period pro! 🗑️ And remember, pads come in different sizes, so pick the one that feels just right for you. Easy, comfy, and you're in charge! 💪🩸",
"Stain S.O.S.: Dress Edition",
"Oops, a period stain? No biggie! Act fast: grab some cold water and gently blot the stain. 💦 If you're a detective with a backpack, a sweater around your waist works wonders. 🧥 Head to the bathroom, use soap and cold water to tackle the stain ninja-style. 🚽 In a pinch? Embrace strategic layering or borrow a friend's emergency hoodie. 👚 Remember, stains happen – you're a stain superhero in the making! 💪🩸",
"Period Products 101: Your Handy Guide",
"Periods come with a variety of products to suit your comfort. \n\n1. Pads: First up, we've got pads. These babies are made of comfy cotton and come in all shapes and sizes. They've got sticky strips to keep them in place on your undies. Super easy and reliable! 👍 Stick them in your undies for a comfy layer. Change as needed.\n\n2. Tampons: These little wonders go inside, soaking up the flow. Choose the size that fits your flow level. 🌊 These can be a game-changer, especially for active girls into sports or swimming. Tampons are like little cotton plugs that you insert into your vagina. They come with handy applicators to help you out. Remember, though, never leave a tampon in for more than 8 hours to avoid a rare but serious infection called toxic shock syndrome. ⏰\n\n3. Menstrual Cups: Like a reusable superhero, they collect the flow. Fold, insert, and you're good for hours. ♻️ These are made of silicone and are reusable, which is pretty cool! You just pop it in, and it collects the blood until you're ready to empty it out. Plus, it's eco-friendly! 🌱\n\n4. Period Panties:Underwear with built-in magic. They handle light to moderate flows without any extra help. 👙\n\n5. Period Discs: A bit like a frisbee for your flow. Collect it internally, and you can forget about it for a while. 🥏\n\nRemember, it's all about what feels right for you. Pick your period partner, and you're ready for the monthly adventure! 🌈🩸✨\n\nSo, there you have it! Experiment a bit and find what feels right for you. Your period, your rules! 💁‍♀️🩸",
"Understanding Physiology",
"Periods Unveiled: The Ultimate Guide for Girls",
"Fear not, period warrior! If Aunt Flow decides to visit during school hours, sneak a stash of pads or tampons in your bag. 🎒 Team up with a trusty friend – a period buddy, if you will – who might have your back with supplies. 🤝 If the unexpected happens, don't panic; most schools have discreetly stocked bathrooms or a helpful nurse. 🚽 Always have a secret weapon, like a cozy sweater tied around your waist, just in case. 🧥 And remember, you're not alone – we've all been there, and it's just another day in the life of a period pro! 💪🩸",
"Welcome to the world of periods – a monthly adventure! 🎉 First up, meet your trusty companions: pads, tampons, or menstrual cups. 🩸 Track your cycle with apps or old-school calendars; knowledge is power. 📅 Embrace comfy clothes, a hot water bottle, and maybe some chocolate during the monthly fiesta. 🍫 Don't fear stains – tackle them with cold water and a superhero mindset. 💦 Chat with trusted pals or adults if you need backup. 🗣️ Remember, periods are your body's way of saying, 'Hey, I'm amazing!' 💁 You're in control, period pro! 💪🌟",
"Decoding PMS: The Monthly Guest",
"FAQs and Common Myths",
"PMS stands for Premenstrual Syndrome – a tag-along companion that visits before your period. 🚶‍♀️ It brings a mix of physical and emotional sidekicks, like mood swings, cramps, and bloating. 😩 Think of it as your body's way of giving you a heads-up that the period party is on its way. 🎉 Chocolate cravings, tender feelings, and occasional superhero mood swings may join the parade. 🍫 Don't worry; it's all part of the monthly script. 📜 Treat yourself kindly, maybe with a chocolate bar, and ride the PMS wave like the period pro you are! 🌊🍫🌟",
"Can a Girl Get Pregnant as Soon as Her Period Starts?",
"Yes, a girl can get pregnant as soon as her period starts. 🤰 A girl can even get pregnant right before her very first period. 🔄 This is because a girl's hormones might already be active. 💫 The hormones may have led to ovulation and the building of the uterine wall. 🏗️ If a girl has sex, she can get pregnant, even though she has never had a period. 🚼",
'Managing Period Pain and Support',
"Cramp 101: Taming Period Pain",
"Period cramps are like tiny workouts for your tummy – not the best guests, right? 💔 Fight back with a warm pad on your belly or some pain relievers if needed. 🔥 Drink water to stay hydrated – it's like your secret weapon. 💧 Try easy exercises like stretching or yoga; they're like superhero moves against cramps. 🧘‍♀️ Find a comfy spot, watch your favorite shows, and relax. 📺 Remember, you're the boss of those cramps; they won't stick around forever. 💪🩸",
"Period Sidekick 101: A Pocket Guide",
"Supporting friends during their periods is a breeze! 💨 Step one: stock up on chocolate, the ultimate comfort treat. 🍫 Offer cozy comforts like a heating pad and ace the art of blanket nests. 🛌 Be the distraction guru with jokes or cute videos. 🤣 You're not just a friend; you're the superhero in their period saga! 💪🩸",
"Periods at School: A Quick Survival Guide",
"First Period Party: Your Quick Guide",
"Congrats on joining the period club! 🎉 Step one: Don't panic; it's a natural superhero skill. 💪 Check for supplies – pads or tampons – and if you're unsure, a trusted friend or an understanding adult can be your sidekick. 🦸 Embrace comfy vibes with loose clothes and maybe a hot water bottle. 🌡️ Celebrate this rite of passage – you're officially a period pro! 💫🩸",
"Menopause Mystery Unveiled",
"Menopause is like the grand finale in the womanhood journey. 🎉 It's when the ovaries decide to take a break from their egg-producing gig. 🥚 Typically hitting in the late 40s or early 50s, menopause brings a pause to the menstrual party. 🎉 Say farewell to periods, but hello to new adventures! 👋 Alongside this change, hormonal shifts might bring hot flashes, mood swings, and other cameo appearances. 🔥 Don't fret; it's a natural part of the life plot. 📖 Embrace it with grace, maybe a fan for hot flashes, and know that you're entering a new chapter – the wise and wonderful world of post-menopause. 🚪🚶‍♀️🌅",
"Profile",
"Favorite Blogs",
"Choose language",
"Select the Language That Best Suits Your Preferences",
"Liked Videos",
"No blogs found",
"Registered Events",
"Explore Your Written Insights",
"Curate Your Preferred Reads",
"Stay Updated on Your Engagements",
"Starred Articles",
"Access Your Starred Reads",
"Keep Your Preferred Videos Handy",
];