List<String> originalStrings = [
"Explore seu ciclo",
"Acesse recursos educacionais e conteúdo valioso para uma jornada menstrual mais saudável.",
"Seu guia pessoal",
"Conheça Paddy, seu companheiro pessoal de chatbot - faça perguntas livremente, mantenha segredos privados e receba conselhos personalizados.",
"Capacitar a mudança por meio de doação e engajamento",
"Apoie causas, compartilhe histórias e conecte-se com pessoas que pensam como você",
'Higiene Menstrual',
"E-mail",
"Senha",
"Lembre de mim",
"Esqueceu sua senha?",
"Entrar",
"Criar uma conta",
"Conectar com Período",
"Junte-se à nossa comunidade para obter suporte e recursos personalizados para a saúde menstrual.",
"Ou faça login com",
"Pular",
"Digite seu e-mail para receber instruções sobre como redefinir sua senha e recuperar o acesso ao Período.",
"Enviar",
"E-mail de redefinição de senha enviado",
"A segurança da sua conta é nossa prioridade! Enviamos a você um link seguro para alterar sua senha com segurança e manter sua conta protegida.",
"Feito",
"Reenviar email",
"Primeiro nome",
"Sobrenome",
"Nome de usuário",
"Telefone não.",
"Criar uma conta",
"ou inscreva-se com",
"Verifique seu endereço de e-mail",
"Confirme seu endereço de e-mail para desbloquear acesso total aos recursos de saúde menstrual do Period.",
"Seu e-mail foi verificado com sucesso. Aproveite acesso total aos recursos de saúde menstrual e suporte da comunidade.",
"Continuar",
"Reenviar email",
"Digite mensagem",
"Categorias",
'Organizador',
'Campanhas',
"Eventos",
"Pesquisar organizações",
'Guia para iniciantes sobre saúde menstrual',
'Vídeos em Destaque',
'Artigos Mais Recentes',
'Detalhes do curso',
'Introdução',
'O que é menopausa',
'O que as mulheres têm desconforto?',
'Alterar foto do perfil',
'Informação do Perfil',
'Nome',
'Informações pessoais',
'Data de nascimento',
"Conta",
'Configurações de Conta',
"Recursos Marcados",
"Minhas Doações",
"Meus blogs",
"Campanhas favoritas",
"Blogs salvos",
"Acompanhe suas contribuições",
"Suas experiências em um só lugar",
"Fique conectado às causas próximas ao seu coração",
"Suas leituras favoritas",
"Explore seus tesouros educacionais salvos",
'Configurações do aplicativo',
"Mudar idioma",
"Adapte sua experiência com uma mudança de idioma",
"Bem-vindo ao período!",
"O que são períodos?",
"Adicionado a blogs curtidos",
"Falha ao adicionar blogs favoritos",
"Descrição",
"Nenhum evento encontrado",
"DOE agora",
"Consulte Mais informação",
"Você está dentro!",
"Obrigado por participar do evento de doações. Seu apoio faz a diferença!",
"Registro",
"Carregar Blog",
"Enviar Imagem",
"Título",
"Contente",
"Categoria",
"Falha ao carregar a postagem do blog",
"Carregar Blog",
"Pesquisar blogs",
"Últimos Blogs",
"Como você está?",
"Hoje",
"Sentindo-se generoso",
"Campanha não encontrada",
"Evento não encontrado",
"Pesquisar recursos",
"Introdução à Saúde Menstrual",
"Introdução: O que são períodos?",
"Impacto da Saúde Menstrual na Vida Diária",
"Ei, meninas! Então, vamos falar sobre menstruação, ou como chamamos, menstruação! É uma coisa mensal que acontece conosco, mulheres. Basicamente, é quando um pouco de sangue e tecido sai do nosso útero através da vagina. Geralmente entra em ação por volta dos 12 anos, mas, ei, é diferente para cada pessoa - alguns podem começar mais cedo, outros mais tarde. Mas não se preocupe, tudo faz parte do crescimento e da preparação para possíveis aventuras de criação de bebês mais tarde! 😊 Durante esse período, você pode sentir todos os tipos de emoções e talvez algum desconforto, mas não se preocupe! Existem maneiras de lidar com isso e geralmente dura apenas alguns dias. É muito importante saber sobre a menstruação para que você possa cuidar de si mesma e sinta-se confortável conversando sobre isso com adultos de confiança. 🌸 \n\n Agora, vamos entrar no âmago da questão! Então, a menstruação acontece porque nossos corpos são superinteligentes e cheios de hormônios, que são como pequenos mensageiros enviando sinais. Os ovários liberam dois hormônios especiais chamados estrogênio e progesterona. Esses hormônios fazem uma coisa legal: tornam o revestimento do útero todo aconchegante e espesso, como uma bela cama para um bebê em potencial. Mas se não houver nenhum bebê a caminho, esse revestimento se rompe e diz tchau, causando o sangramento. Então todo o ciclo recomeça! É como uma festa dançante mensal para nossos corpos! 💃🩸",
"Quando vou ter minha primeira menstruação?",
"Perguntas frequentes e mitos comuns",
"Então, a maioria das meninas geralmente começa a menstruar por volta dos 12 anos, mas quer saber? É totalmente legal se isso acontecer entre 10 e 15 anos. ! Não há uma idade definida para que isso aconteça, mas há alguns indícios de que isso pode estar a caminho: tipo, muitas vezes, cerca de 2 anos depois que seus seios começam a crescer, você pode notar que sua menstruação está aparecendo. Além disso, tem essa coisa chamado corrimento vaginal, que é como um muco, que você pode ver ou sentir na sua calcinha. Não se preocupe, é tudo apenas o seu corpo se preparando para essa nova aventura! 🌟 Então, sempre que acontecer, é só seguir em frente! Seu corpo sabe o que está fazendo. 💪",
'Qual é a sensação do primeiro período?',
"Saúde Menstrual e Bem-Estar Mental",
"Ei, garota! Então, quando você menstrua, é como se seu corpo desse uma festinha todo mês! 🎉 Mas, ei, é totalmente normal se você se sentir um pouco mal durante esse período. Algumas garotas têm cólicas ou sentem um poucocansado, mas não se preocupe, tudo faz parte do pacote. Pense nisso como seu corpo fazendo seu trabalho, se preparando para quaisquer aventuras que surgirem em seu caminho! 💪 E ei, nem tudo é ruim! Você pode arrasar com algumas calcinhas de época fofas ou experimentar alguns produtos divertidos de época! 🩲 Então, abrace o fluxo, garota! E lembre-se, tudo faz parte de crescer e ser incrível! 🌸💖",
"Higiene e Gestão Menstrual",
"Higiene do Período 101: Manual da Rainha Limpa?",
"A higiene reina suprema durante a menstruação! Comece com trocas frequentes de absorventes, absorventes internos ou copos - os heróis desconhecidos. 🩸 Lave as mãos antes e depois, tornando você a estrela da higiene. 🧼 Opte por lenços ou produtos de limpeza suaves e sem fragrância. 🌸 Mantenha o sagrado 'arsenal de roupas íntimas' abastecido e troque conforme necessário. 💪 Aproveite o poder dos chuveiros – eles são seus companheiros de época. 🚿 Por fim, evite a tentação de dar descarga nos absorventes – deixe o lixo ser seu destino final. 🚫 Você está não apenas mantendo a higiene; você é uma rainha limpa governando seu domínio menstrual!",
"Pad Power: seu companheiro de menstruação",
"Os absorventes são como escudos mágicos para a menstruação. 🛡️ Retire um da embalagem, coloque-o na calcinha (lado adesivo voltado para baixo) e pronto. Troque-o a cada 4-6 horas ou antes, se estiver cheio. ⏰ Quando estiver hora de se separar, embrulhe-o em papel higiênico, jogue-o no lixo (não no banheiro) e ta-da – você é um profissional do período! 🗑️ E lembre-se, absorventes vêm em tamanhos diferentes, então escolha aquele que se sente melhor. ideal para você. Fácil, confortável e você está no comando! 💪🩸",
"Stain S.O.S.: Edição de Vestido",
"Opa, uma mancha de menstruação? Nada demais! Aja rápido: pegue um pouco de água fria e seque suavemente a mancha. 💦 Se você é um detetive com uma mochila, um suéter na cintura faz maravilhas. 🧥 Vá para o banheiro, use sabonete e água fria para lidar com a mancha no estilo ninja. 🚽 Em apuros? Adote camadas estratégicas ou peça emprestado o moletom de emergência de um amigo. 👚 Lembre-se, manchas acontecem – você é um super-herói de manchas em formação! 💪🩸",
"Produtos do período 101: seu guia prático",
"A menstruação vem com uma variedade de produtos para se adequar ao seu conforto. \n\n1. Almofadas: primeiro, temos almofadas. Esses bebês são feitos de algodão confortável e vêm em todos os formatos e tamanhos. Eles têm tiras adesivas para mantê-los no lugar em sua calcinha. Muito fácil e confiável! 👍 Cole-os em sua calcinha para obter uma camada confortável. Troque conforme necessário.\n\n2. Absorventes internos: essas pequenas maravilhas ficam dentro, absorvendo o fluxo. Escolha o tamanho que se adapta ao seu nível de fluxo. 🌊 Eles podem ser uma virada de jogo, especialmente para meninas ativas que praticam esportes ou natação. Os absorventes internos são como pequenos tampões de algodão que você insere na vagina. Eles vêm com aplicadores úteis para ajudá-la. Lembre-se, no entanto , nunca deixe um absorvente interno por mais de oito horas para evitar uma infecção rara, mas grave, chamada síndrome do choque tóxico. ⏰\n\n3. Copos menstruais: como um super-herói reutilizável, eles coletam o fluxo. Dobre, insira e você estará pronto. bom por horas. ♻️ Eles são feitos de silicone e são reutilizáveis, o que é muito legal! Basta colocá-lo e ele coleta o sangue até que você esteja pronto para esvaziá-lo. Além disso, é ecológico! 🌱\n\n4. Calcinha de época: Roupa íntima com magia embutida. Eles lidam com fluxos leves a moderados sem qualquer ajuda extra. 👙\n\n5. Discos de período: um pouco como um frisbee para o seu fluxo. Colete-o internamente e você poderá esquecê-lo por um tempo. 🥏\n\nLembre-se: tudo se resume ao que parece certo para você. Escolha seu parceiro menstrual e você estará pronto para a aventura mensal! 🌈🩸✨\n\nEntão, aí está! Experimente um pouco e descubra o que parece certo para você. Seu período, suas regras! 💁‍♀️🩸",
"Compreendendo a Fisiologia",
"Períodos revelados: o guia definitivo para meninas",
"Não tenha medo, guerreiro do período! Se tia Flow decidir visitá-lo durante o horário escolar, guarde um estoque de absorventes ou absorventes internos em sua bolsa. 🎒 Junte-se a um amigo de confiança - um companheiro de período, se preferir - que pode ajudá-lo suprimentos. 🤝 Se o inesperado acontecer, não entre em pânico; a maioria das escolas tem banheiros discretamente abastecidos ou uma enfermeira prestativa. 🚽 Sempre tenha uma arma secreta, como um suéter aconchegante amarrado na cintura, só para garantir. 🧥 E lembre-se, você' não estamos sozinhos – todos nós já passamos por isso e é apenas mais um dia na vida de um profissional de menstruação! 💪🩸",
"Bem-vindo ao mundo da menstruação – uma aventura mensal! 🎉 Primeiro, conheça seus companheiros de confiança: absorventes, absorventes internos ou copos menstruais. 🩸 Acompanhe seu ciclo com aplicativos ou calendários tradicionais; conhecimento é poder. 📅 Abrace roupas confortáveis, uma bolsa de água quente e talvez um pouco de chocolate durante a festa mensal. 🍫 Não tenha medo de manchas – enfrente-as com água fria e uma mentalidade de super-herói. 💦 Converse com amigos ou adultos de confiança se precisar de apoio. 🗣️ Lembre-se, a menstruação é do seu corpo. maneira de dizer: 'Ei, sou incrível!' 💁 Você está no controle, ponto final! 💪🌟",
"Decodificando PMS: O Convidado Mensal",
"Perguntas frequentes e mitos comuns",
"TPM significa Síndrome Pré-Menstrual - um companheiro que vem antes da menstruação. 🚶‍♀️ Traz uma mistura de companheiros físicos e emocionais, como alterações de humor, cólicas e inchaço. 😩 Pense nisso como a maneira do seu corpo dar vocêum aviso de que a festa da época está a caminho. 🎉 Desejos de chocolate, sentimentos de ternura e ocasionais mudanças de humor de super-heróis podem participar do desfile. 🍫 Não se preocupe; tudo faz parte do roteiro mensal. 📜 Mime-se com gentileza, talvez com uma barra de chocolate, e pegue a onda da TPM como o profissional do período que você é! 🌊🍫🌟",
"Uma menina pode engravidar assim que começa a menstruação?",
"Sim, uma menina pode engravidar assim que a menstruação começa. 🤰 Uma menina pode até engravidar logo antes da primeira menstruação. 🔄 Isso ocorre porque os hormônios da menina já podem estar ativos. 💫 Os hormônios podem ter levado à ovulação e a construção da parede uterina. 🏗️ Se uma menina fizer sexo, ela pode engravidar, mesmo que nunca tenha menstruado. 🚼",
'Gerenciando dor e suporte menstrual',
"Cãibra 101: Domar a dor menstrual",
"As cólicas menstruais são como pequenos exercícios para a barriga - não são os melhores convidados, certo? 💔 Lute com uma almofada quente na barriga ou alguns analgésicos, se necessário. 🔥 Beba água para se manter hidratado - é como sua arma secreta. 💧 Experimente exercícios fáceis como alongamento ou ioga; eles são como movimentos de super-heróis contra cólicas. 🧘‍♀️ Encontre um local confortável, assista seus programas favoritos e relaxe. 📺 Lembre-se, você é o chefe dessas cólicas; elas não vão durar por aqui para sempre. 💪🩸",
"Period Sidekick 101: um guia de bolso",
"Apoiar os amigos durante a menstruação é muito fácil! 💨 Primeiro passo: estocar chocolate, o melhor conforto. 🍫 Ofereça confortos aconchegantes, como uma almofada térmica e arrase na arte dos ninhos de cobertor. 🛌 Seja o guru da distração com piadas ou vídeos fofos . 🤣 Você não é apenas um amigo; você é o super-herói da saga de época deles! 💪🩸",
"Períodos na escola: um guia rápido de sobrevivência",
"Festa do primeiro período: seu guia rápido",
"Parabéns por ingressar no clube do período! 🎉 Primeiro passo: não entre em pânico; é uma habilidade natural do super-herói. 💪 Verifique se há suprimentos - absorventes ou absorventes internos - e se não tiver certeza, um amigo de confiança ou um adulto compreensivo pode ser seu ajudante . 🦸 Abrace vibrações confortáveis com roupas largas e talvez uma bolsa de água quente. 🌡️ Comemore este rito de passagem – você é oficialmente um profissional de menstruação! 💫🩸",
"O mistério da menopausa revelado",
"A menopausa é como o grande final na jornada da feminilidade. 🎉 É quando os ovários decidem fazer uma pausa na produção de óvulos. 🥚 Normalmente chegando no final dos 40 ou início dos 50, a menopausa traz uma pausa para a festa menstrual. Diga adeus à menstruação, mas olá para novas aventuras! 👋 Juntamente com essa mudança, as mudanças hormonais podem trazer ondas de calor, alterações de humor e outras aparições. 🔥 Não se preocupe; é uma parte natural do enredo da vida. 📖 Abrace-o com Grace, talvez seja fã de ondas de calor, e saiba que você está entrando em um novo capítulo – o sábio e maravilhoso mundo da pós-menopausa. 🚪🚶‍♀️🌅",
"Perfil",
"Blogs favoritos",
"Escolha o seu idioma",
"Selecione o idioma que melhor se adapta às suas preferências",
"Vídeos curtidos",
"Nenhum blog encontrado",
"Eventos Registrados",
"Explore suas percepções escritas",
"Selecione suas leituras preferidas",
"Mantenha-se atualizado sobre seus compromissos",
"Artigos estrelados",
"Acesse suas leituras com estrela",
"Mantenha seus vídeos preferidos à mão",
];
