List<String> originalStrings = [
  "Empowering Farmers Through Education",
  "Providing Comprehensive Education and Resources to Empower Farmers in Cultivating Sustainable Agriculture.",
  "Your Farming Companion",
  "Introducing Krishi Bindu: Your Personalized Farming Assistant — Seek Guidance, Exchange Insights, and Cultivate Success Together!",
  "EnablingFarmers for Sustainable Growth with a community",
  "Access Comprehensive Resources, Foster Vibrant Community Networks, and Cultivate Success Together",
  'Good Morning',
  "E-Mail",
  "Password",
  "Remember me",
  "Forgot Password?",
  "Sign In",
  "Create Account",
  "Connect with Krishi Bindu",
  "Join our network for tailored agricultural guidance and resources, empowering your farming journey.",
  "Or Sign In with",
  "Skip",
  "Enter your email to receive instructions on resetting your password and regain access to our app.",
  "Submit",
  "Password Reset Email Sent",
  "Your account security is our priority! We've sent you a secure link to safely change your password and keep your account protected.",
  "Done",
  "Resend Email",
  "First Name",
  "Last Name",
  "Username",
  "Phone No.",
  "Create account",
  "View all",
  "Verify your email address",
  "Confirm your email address to unlock full access to resources.",
  "Your email has been successfully verified. Enjoy full access to agricultural resources and community support.",
  "Continue",
  "Resend Email",
  "Type message",
  "Categories",
  'Organiser',
  'Campaigns',
  "Schemes",
  "Search Organizations",
  'Chat with Sevak',
  'Featured Techniques',
  'Latest Articles',
  'Upcoming Schemes',
  'NGOs',
  'New Campaigns',
  'What do women have discomfort?',
  'Change profile picture',
  'Profile Information',
  'Name',
  'Personal Information',
  'Date of Birth',
  "Account",
  'Account Settings',
  "Bookmarked Resources",
  "My Donations",
  "My Blogs",
  "Favorite Campaigns",
  "Saved Blogs",
  "Track your contributions",
  "Your experiences at one place",
  "Stay connected to causes close to your heart",
  "Your favorite reads",
  "Explore your saved educational treasures",
  'App Settings',
  "Change language",
  "Tailor your experience with a language switch",
  "Welcome to Period!",
  "What are periods?",
  "Added to liked blogs",
  "Failed to add to liked blogs",
  "Description",
  "No events found",
  "Donate now",
  "Read more",
  "You're In!",
  "Thank you for joining the donation event. Your support makes a difference!",
  "Register",
  "Upload Blog",
  "Upload Image",
  "Title",
  "Content",
  "Category",
  "Failed to upload blog post",
  "Upload Blog",
  "Search Blogs",
  "Latest Blogs",
  "How you doing?",
  "Today",
  "Feeling Generous,",
  "Campaign not found",
  "Event not found",
  "Search Resources",
  "Contribute",
  "Home",
  "Blogs",
  "Chat",
  "Videos",
  "Profile",
  "Favorite Blogs",
  "Choose language",
  "Select the Language That Best Suits Your Preferences",
  "Liked Videos",
  "No blogs found",
  "Registered Events",
  "Explore Your Written Insights",
  "Curate Your Preferred Reads",
  "Stay Updated on Your Engagements",
  "Starred Articles",
  "Access Your Starred Reads",
  "Keep Your Preferred Videos Handy",
  "New Campaigns",
  "Upcoming Schemes",
];
