List<String> originalStrings = [
  "Explora tu ciclo",
  "Acceda a recursos educativos y contenido valioso para un viaje menstrual más saludable.",
  "Tu guía personal",
  "Conozca a Paddy, su compañero personal de chatbot: haga preguntas libremente, mantenga los secretos en privado y obtenga asesoramiento personalizado.",
  "Potenciar el cambio a través de la donación y el compromiso",
  "Apoye causas, comparta historias y conéctese con personas de ideas afines",
  "Higiene menstrual",
  "Correo electrónico",
  "Contraseña",
  "Acuérdate de mí",
  "¿Has olvidado tu contraseña?",
  "Iniciar sesión",
  "Crear una cuenta",
  "Conéctate con el punto",
  "Únase a nuestra comunidad para obtener apoyo y recursos personalizados para la salud menstrual.",
  "O iniciar sesión con",
  "Saltar",
  "Ingrese su correo electrónico para recibir instrucciones sobre cómo restablecer su contraseña y recuperar el acceso a Period.",
  "Entregar",
  "Correo electrónico de restablecimiento de contraseña enviado",
  "¡La seguridad de su cuenta es nuestra prioridad! Le hemos enviado un enlace seguro para cambiar su contraseña de forma segura y mantener su cuenta protegida.",
  "Hecho",
  "Reenviar email",
  "Nombre de pila",
  "Apellido",
  "Nombre de usuario",
  "Telefono no.",
  "Crear una cuenta",
  "o regístrate con",
  "Verifique su dirección de correo electrónico",
  "Confirma tu dirección de correo electrónico para desbloquear el acceso completo a los recursos de salud menstrual de Period.",
  "Su correo electrónico ha sido verificado exitosamente. Disfrute de acceso completo a recursos de salud menstrual y apoyo comunitario.",
  "Continuar",
  "Reenviar email",
  "Escribir mensaje",
  "Categorías",
  "Organizador",
  "Campañas",
  "Eventos",
  "Buscar Organizaciones",
  "Guía para principiantes sobre la salud menstrual",
  "Vídeos destacados",
  "Últimos artículos",
  "Detalles del curso",
  "Introducción",
  "¿Qué es la menopausia?",
      "¿Qué molestias tienen las mujeres?",
  "Cambiar foto de perfil",
  "Información del perfil",
  "Nombre",
  "Informacion personal",
  "Fecha de nacimiento",
  "Cuenta",
  "Configuraciones de la cuenta",
  "Recursos marcados",
  "Mis Donaciones",
  "Mis blogs",
  "Campañas favoritas",
  "Blogs guardados",
  "Seguimiento de tus contribuciones",
  "Tus experiencias en un solo lugar",
  "Manténgase conectado con causas cercanas a su corazón",
  "Tus lecturas favoritas",
  "Explora tus tesoros educativos guardados",
  "Ajustes de Aplicacion",
  "Cambiar idioma",
  "Personaliza tu experiencia con un cambio de idioma",
  "¡Bienvenidos al punto!",
  "¿Qué son los períodos?",
      "Agregado a los blogs que me gustan",
  "No se pudo agregar a los blogs que me gustan",
  "Descripción",
  "No se encontraron eventos",
  "Done ahora",
  "Leer más",
  "¡Estas en!",
  "Gracias por unirte al evento de donación. ¡Tu apoyo hace la diferencia!",
  "Registro",
  "Subir blog",
  "Cargar imagen",
  "Título",
  "Contenido",
  "Categoría",
  "Error al cargar la publicación del blog",
  "Subir blog",
  "Buscar blogs",
  "Últimos blogs",
  "¿Cómo estás?",
  "Hoy",
  "Sentirse generoso",
  "Campaña no encontrada",
  "Evento no encontrado"," ",
  "Buscar recursos",
  "Introducción a la Salud Menstrual",
  "Introducción: ¿Qué son los períodos?",
  "Impacto de la Salud Menstrual en la Vida Cotidiana",
  "¡Hola chicas! Entonces, hablemos de períodos, o como lo llamamos, ¡menstruación! Es algo mensual que nos sucede a nosotras, las mujeres. Básicamente, es cuando algo de sangre y tejido sale de nuestro útero a través de la vagina. Por lo general, se activa alrededor cuando tienes 12 años, pero bueno, es diferente para cada persona: algunos pueden comenzar antes, otros más tarde. ¡Pero no te preocupes, todo es parte del crecimiento y la preparación para posibles aventuras de tener bebés más adelante! 😊 Durante este tiempo, Es posible que sientas todo tipo de emociones y tal vez algunas molestias, ¡pero no te preocupes! Hay formas de manejarlo y suele durar solo unos días. Es muy importante conocer la regla para que puedas cuidarte y cuidarte. siéntete cómoda conversando sobre ello con adultos de confianza. 🌸 \n\n ¡Ahora, entremos en el meollo de la cuestión! Entonces, los períodos ocurren porque nuestros cuerpos son súper inteligentes y están llenos de hormonas, que son como pequeños mensajeros que envían señales. Los ovarios liberan Dos hormonas especiales llamadas estrógeno y progesterona, que hacen algo interesante: hacen que el revestimiento de nuestro útero sea acogedor y grueso, como una bonita cama para un bebé potencial. Pero si no hay ningún bebé en camino, ese revestimiento se rompe y dice adiós, provocando el sangrado. ¡Entonces todo el ciclo comienza de nuevo! ¡Es como una fiesta de baile mensual para nuestros cuerpos! 💃🩸",
  "¿Cuándo tendré mi primer período?",
  "Preguntas frecuentes y mitos comunes",
  "Entonces, la mayoría de las niñas generalmente comienzan a tener su primer período cuando tienen alrededor de 12 años, pero ¿sabes qué? Es totalmente genial si ocurre en cualquier momento entre los 10 y los 15. 🎉 Tu cuerpo simplemente tiene su propio horario y hace lo suyo. No hay una edad establecida para que esto suceda, pero hay algunos indicios de que podría estar en camino: por ejemplo, a menudo, aproximadamente 2 años después de que tus senos comiencen a crecer, es posible que notes que aparece tu período. Además, existe esta cosa. llamado flujo vaginal, que es algo así como moco, que puedes ver o sentir en tu ropa interior. ¡No te preocupes, es solo tu cuerpo preparándose para esta nueva aventura! 🌟 Así que, cuando suceda, ¡simplemente sigue adelante! Tu cuerpo sabe lo que hace. 💪",
  "¿Cómo se siente el primer período?",
  "Salud Menstrual y Bienestar Mental",
  "¡Hola niña! Entonces, cuando tienes tu período, ¡es como si tu cuerpo organizara una pequeña fiesta cada mes! 🎉 Pero bueno, es totalmente normal si te sientes un poco rara durante este tiempo.Algunas niñas tienen calambres o se sienten un poco cansadas, pero no te preocupes, todo es parte del paquete. ¡Piensa en ello como si tu cuerpo hiciera lo suyo, preparándose para cualquier aventura que se te presente! 💪 ¡Y oye, no todo es malo! ¡Quizás puedas lucir lindas prendas íntimas de época o probar algunos productos divertidos de época! 🩲 ¡Así que abraza la corriente, niña! Y recuerda, ¡todo es parte de crecer y ser increíble! 🌸💖 ",
"Higiene y Manejo Menstrual",
"Higiene menstrual básica: ¿un manual para una reina limpia?",
"¡La higiene reina durante tu período! Comienza con cambios frecuentes de toallas sanitarias, tampones o copas: los héroes anónimos. 🩸 Lávate las manos antes y después, lo que te convierte en la superestrella de la higiene. 🧼 Opta por toallitas o limpiadores suaves y sin fragancia. 🌸 Mantenga abastecido el sagrado 'arsenal de ropa interior' y cámbielo según sea necesario. 💪 Abrace el poder de las duchas: son sus compañeras de período. 🚿 Finalmente, evite la tentación de tirar las toallas sanitarias al inodoro: deje que la basura sea su destino final. 🚫 Estás no sólo mantener la higiene; ¡eres una reina limpia que gobierna tu dominio menstrual!",
"Pad Power: tu compañero de período",
"Las toallas sanitarias son como escudos mágicos para tu período. 🛡️ Saca una de su envoltorio, colócala en tu ropa interior (con el lado adhesivo hacia abajo) y listo. Cámbiala cada 4 a 6 horas o antes si está llena. ⏰ Cuando esté Es hora de separarse, envuélvelo en papel higiénico, tíralo a la basura (no al inodoro) y ta-da: ¡eres un profesional del período! 🗑️ Y recuerda, las toallas sanitarias vienen en diferentes tamaños, así que elige la que se sienta mejor. perfecto para ti. ¡Fácil, cómodo y tú estás a cargo! 💪🩸",
"Stain S.O.S.: Edición de vestidos",
"Ups, ¿una mancha menstrual? ¡No es gran cosa! Actúa rápido: toma un poco de agua fría y seca suavemente la mancha. 💦 Si eres un detective con una mochila, un suéter alrededor de tu cintura funciona de maravilla. 🧥 Dirígete al baño, usa jabón y agua fría para combatir las manchas al estilo ninja. 🚽 ¿En caso de apuro? Adopta capas estratégicas o pide prestada la sudadera con capucha de emergencia de un amigo. 👚 Recuerda, las manchas suceden: ¡eres un superhéroe en ciernes! 💪🩸",
"Productos de época 101: su guía práctica",
"La regla viene con una variedad de productos que se adaptan a tu comodidad. \n\n1. Toallas sanitarias: primero, tenemos toallas sanitarias. Estos bebés están hechos de cómodo algodón y vienen en todas las formas y tamaños. Tienen tiras adhesivas. para mantenerlos en su lugar en la ropa interior. ¡Súper fáciles y confiables! 👍 Pégalos en la ropa interior para obtener una capa cómoda. Cámbialos según sea necesario.\n\n2. Tampones: estas pequeñas maravillas van adentro y absorben el flujo. Elige el tamaño que se ajuste a tu nivel de flujo. 🌊 Estos pueden cambiar las reglas del juego, especialmente para las chicas activas que practican deportes o nadan. Los tampones son como pequeños tapones de algodón que se insertan en la vagina. Vienen con prácticos aplicadores para ayudarte. Recuerda, sin embargo , nunca dejes un tampón puesto por más de 8 horas para evitar una infección rara pero grave llamada síndrome de shock tóxico. ⏰\n\n3. Copas menstruales: como un superhéroe reutilizable, recogen el flujo. Dobla, inserta y listo. bueno por horas. ♻️ Estos están hechos de silicona y son reutilizables, ¡lo cual es genial! Simplemente lo introduces y recoge la sangre hasta que estés listo para vaciarla. Además, ¡es ecológico! 🌱\n\n4. Bragas de época: Ropa interior con magia incorporada. Manejan flujos de ligeros a moderados sin ninguna ayuda adicional. 👙\n\n5. Discos de época: un poco como un disco volador para tu flujo. Recójalo internamente y podrá olvidarse de él por un tiempo. 🥏\n\nRecuerda, todo se trata de lo que te parezca adecuado. ¡Elige tu compañero de período y estarás listo para la aventura mensual! 🌈🩸✨\n\n¡Ahí lo tienes! Experimente un poco y encuentre lo que le parezca adecuado. ¡Tu período, tus reglas! 💁‍♀️🩸",
"Comprensión de la fisiología",
"Períodos revelados: la guía definitiva para niñas",
"¡No temas, guerrera de la menstruación! Si la tía Flow decide visitarte durante el horario escolar, guarda un montón de toallas sanitarias o tampones en tu bolso. 🎒 Forma equipo con un amigo de confianza (un compañero de menstruación, por así decirlo) que pueda respaldarte. suministros. 🤝 Si ocurre algo inesperado, no entre en pánico; la mayoría de las escuelas tienen baños discretamente abastecidos o una enfermera servicial. 🚽 Tenga siempre un arma secreta, como un suéter cómodo atado a su cintura, por si acaso. 🧥 Y recuerde, usted No estás solo: todos hemos pasado por eso y ¡es solo un día más en la vida de un profesional de la época! 💪🩸",
"Bienvenido al mundo de la menstruación: ¡una aventura mensual! 🎉 En primer lugar, conoce a tus compañeros de confianza: toallas sanitarias, tampones o copas menstruales. 🩸 Sigue tu ciclo con aplicaciones o calendarios de la vieja escuela; el conocimiento es poder. 📅 Adopta ropa cómoda, una bolsa de agua caliente y tal vez un poco de chocolate durante la fiesta mensual. 🍫 No temas a las manchas: trátalas con agua fría y una mentalidad de superhéroe. 💦 Charla con amigos o adultos de confianza si necesitas apoyo. 🗣️ Recuerda, los períodos son de tu cuerpo forma de decir: '¡Oye, soy increíble!' 💁 ¡Tú tienes el control y punto profesional! 💪🌟",
"Decodificando el síndrome premenstrual: el invitado del mes",
"Preguntas frecuentes y mitos comunes",
"PMS significa Síndrome Premenstrual, un compañero que te acompaña antes de tu período. 🚶‍♀️ Trae una mezcla de efectos físicos y emocionales, como cambios de humor, calambres e hinchazón. 😩 Piensa enEs la forma que tiene tu cuerpo de avisarte de que la fiesta de la regla está en camino. 🎉 Los antojos de chocolate, los sentimientos tiernos y los ocasionales cambios de humor de superhéroe pueden unirse al desfile. 🍫 No te preocupes; todo es parte del guión mensual. 📜 ¡Date un capricho, tal vez con una barra de chocolate, y súbete a la ola del síndrome premenstrual como un profesional de la menstruación que eres! 🌊🍫🌟",
"¿Puede una niña quedar embarazada tan pronto como comienza su período?",
"Sí, una niña puede quedar embarazada tan pronto como comienza su período. 🤰 Una niña puede incluso quedar embarazada justo antes de su primer período. 🔄 Esto se debe a que es posible que las hormonas de una niña ya estén activas. 💫 Las hormonas pueden haber provocado la ovulación y la construcción de la pared uterina. 🏗️ Si una niña tiene relaciones sexuales, puede quedar embarazada, aunque nunca haya tenido la regla. 🚼",
"Manejo del dolor menstrual y apoyo",
"Calambre 101: Domar el dolor del período",
"Los calambres menstruales son como pequeños ejercicios para tu barriga; no son los mejores invitados, ¿verdad? 💔 Contraataca con una almohadilla tibia en el abdomen o algunos analgésicos si es necesario. 🔥 Bebe agua para mantenerte hidratado, es como tu arma secreta. 💧 Inténtalo ejercicios fáciles como estiramiento o yoga; son como movimientos de superhéroes contra los calambres. 🧘‍♀️ Encuentra un lugar cómodo, mira tus programas favoritos y relájate. 📺 Recuerda, tú eres el jefe de esos calambres; no se quedarán para siempre. 💪🩸",
"Period Sidekick 101: una guía de bolsillo",
"¡Apoyar a tus amigas durante sus períodos es muy fácil! 💨 Paso uno: abastecerse de chocolate, el mejor regalo reconfortante. 🍫 Ofrece comodidades acogedoras como una almohadilla térmica y domina el arte de los nidos de mantas. 🛌 Conviértete en el gurú de la distracción con chistes o videos lindos . 🤣 ¡No eres solo un amigo, eres el superhéroe de su saga de época! 💪🩸",
"Periodos en la escuela: una guía rápida de supervivencia",
"Fiesta del primer período: su guía rápida",
"¡Felicidades por unirte al club de la menstruación! 🎉 Paso uno: no entres en pánico; es una habilidad natural de los superhéroes. 💪 Busca suministros (toallas sanitarias o tampones) y, si no estás seguro, un amigo de confianza o un adulto comprensivo puede ser tu compañero . 🦸 Adopta un ambiente cómodo con ropa holgada y tal vez una bolsa de agua caliente. 🌡️ Celebra este rito de iniciación: ¡eres oficialmente un profesional del período! 💫🩸",
"El misterio de la menopausia al descubierto",
"La menopausia es como el gran final en el viaje hacia la feminidad. 🎉 Es cuando los ovarios deciden tomar un descanso de su trabajo de producción de óvulos. 🥚 La menopausia, que suele llegar a finales de los 40 o principios de los 50, trae una pausa a la fiesta menstrual. 🎉 ¡Dile adiós a los períodos, pero da la bienvenida a nuevas aventuras! 👋 Además de este cambio, los cambios hormonales pueden traer sofocos, cambios de humor y otras apariciones especiales. 🔥 No te preocupes, es una parte natural de la trama de la vida. 📖 Acéptalo con Grace, tal vez una fanática de los sofocos, y debes saber que estás entrando en un nuevo capítulo: el sabio y maravilloso mundo de la posmenopausia. 🚪🚶‍♀️🌅",
"Perfil",
"Blogs favoritos",
"Elige lengua",
"Seleccione el idioma que mejor se adapte a sus preferencias",
"Vídeos que me gustan",
"No se encontraron blogs",
"Eventos registrados",
"Explore sus conocimientos escritos",
"Seleccione sus lecturas preferidas",
"Manténgase actualizado sobre sus compromisos",
"Artículos destacados",
"Acceda a sus lecturas destacadas",
"Tenga a mano sus vídeos preferidos",
];