List<String> originalStrings = [
"Erkunden Sie Ihren Zyklus",
"Greifen Sie auf Bildungsressourcen und wertvolle Inhalte für eine gesündere Menstruationsreise zu.",
"Ihr persönlicher Reiseführer",
"Lernen Sie Paddy kennen, Ihren persönlichen Chatbot-Begleiter – stellen Sie frei Fragen, halten Sie Geheimnisse geheim und erhalten Sie persönliche Ratschläge.",
"Veränderung durch Spende und Engagement ermöglichen",
"Unterstützen Sie Anliegen, teilen Sie Geschichten und vernetzen Sie sich mit Gleichgesinnten",
"Menstruationshygiene",
"Email",
"Passwort",
"Erinnere dich an mich",
"Passwort vergessen?",
"Anmelden",
"Benutzerkonto erstellen",
"Mit Punkt verbinden",
"Treten Sie unserer Community bei, um personalisierte Unterstützung und Ressourcen für die Menstruationsgesundheit zu erhalten.",
"Oder melden Sie sich an mit",
"Überspringen",
"Geben Sie Ihre E-Mail-Adresse ein, um Anweisungen zum Zurücksetzen Ihres Passworts zu erhalten und wieder Zugriff auf Period zu erhalten.",
"Einreichen",
"E-Mail zum Zurücksetzen des Passworts gesendet",
"Die Sicherheit Ihres Kontos hat für uns Priorität! Wir haben Ihnen einen sicheren Link gesendet, mit dem Sie Ihr Passwort sicher ändern und Ihr Konto schützen können.",
"Erledigt",
"E-Mail zurücksenden",
"Vorname",
"Familienname, Nachname",
"Nutzername",
"Telefon-Nr.",
"Benutzerkonto erstellen",
"Oder melden Sie sich an",
"Bestätige deine Email-Adresse",
"Bestätigen Sie Ihre E-Mail-Adresse, um vollen Zugriff auf die Menstruationsgesundheitsressourcen von Period freizuschalten.",
"Ihre E-Mail-Adresse wurde erfolgreich bestätigt. Genießen Sie vollen Zugriff auf Ressourcen zur Menstruationsgesundheit und Community-Unterstützung.",
"Weitermachen",
"E-Mail zurücksenden",
"Nachricht eingeben",
"Kategorien",
"Veranstalter",
"Kampagnen",
"Veranstaltungen",
"Suchorganisationen",
"Leitfaden für Anfänger zur Menstruationsgesundheit",
"Ausgewählte Videos",
"Neueste Artikel",
"Kursdetails",
"Einführung",
"Was sind Wechseljahre",
"Welche Beschwerden haben Frauen?",
"Profilbild ändern",
"Profil Information",
"Name",
"Persönliche Angaben",
"Geburtsdatum",
"Konto",
"Account Einstellungen",
"Mit Lesezeichen versehene Ressourcen",
"Meine Spenden",
"Meine Blogs",
"Lieblingskampagnen",
"Gespeicherte Blogs",
"Verfolgen Sie Ihre Beiträge",
"Ihre Erlebnisse an einem Ort",
"Bleiben Sie mit Anliegen verbunden, die Ihnen am Herzen liegen",
"Ihre Lieblingslektüre",
"Entdecken Sie Ihre gespeicherten Bildungsschätze",
"App Einstellungen",
"Sprache ändern",
"Passen Sie Ihr Erlebnis mit einem Sprachwechsel individuell an",
"Willkommen in der Periode!",
"Was sind Perioden?",
"Zu den Lieblingsblogs hinzugefügt",
"Hinzufügen zu den Blogs, die mir gefallen, ist fehlgeschlagen",
"Beschreibung",
"Keine Veranstaltungen gefunden",
"Spende jetzt",
"Mehr lesen",
"Du bist in!",
"Vielen Dank für Ihre Teilnahme an der Spendenveranstaltung. Ihre Unterstützung macht einen Unterschied!",
"Registrieren",
"Blog hochladen",
"Bild hochladen",
"Titel",
"Inhalt",
"Kategorie",
"Blogbeitrag konnte nicht hochgeladen werden",
"Blog hochladen",
"Blogs durchsuchen",
"Neueste Blogs",
"Wie geht's?",
"Heute",
"Sich großzügig fühlen",
"Kampagne nicht gefunden",
"Ereignis nicht gefunden",
"Ressourcen suchen",
"Einführung in die Menstruationsgesundheit",
"Einführung: Was sind Perioden?",
"Auswirkungen der Menstruationsgesundheit auf das tägliche Leben",
"Hey Mädels! Also, lasst uns über die Periode reden, oder wie wir es nennen, die Menstruation! Es ist eine monatliche Sache, die uns Damen passiert. Im Grunde ist es so, dass etwas Blut und Gewebe aus unserer Gebärmutter durch die Vagina austreten. Normalerweise setzt es ein.“ Etwa, wenn man 12 ist, aber hey, es ist bei jedem anders – manche fangen vielleicht früher an, manche später. Aber keine Sorge, es gehört alles zum Erwachsenwerden und zur Vorbereitung auf mögliche Baby-Abenteuer später! 😊 Während dieser Zeit Möglicherweise verspüren Sie alle möglichen Emotionen und vielleicht ein gewisses Unbehagen, aber machen Sie sich keine Sorgen! Es gibt Möglichkeiten, damit umzugehen, und normalerweise dauert es nur ein paar Tage. Es ist super wichtig, über die Periode Bescheid zu wissen, damit Sie auf sich selbst und Ihre Periode achten können Fühlen Sie sich wohl, mit vertrauenswürdigen Erwachsenen darüber zu plaudern. 🌸 \n\n Kommen wir nun zum Wesentlichen! Die Periode kommt also daher, weil unser Körper superintelligent und mit Hormonen gefüllt ist, die wie kleine Boten sind, die Signale senden. Die Eierstöcke werden freigesetzt zwei spezielle Hormone namens Östrogen und Progesteron. Diese Hormone bewirken diese coole Sache: Sie machen die Gebärmutterschleimhaut ganz gemütlich und dick, wie ein schönes Bett für ein potenzielles Baby. Aber wenn kein Baby unterwegs ist, reißt diese Auskleidung auf und verabschiedet sich, was zu Blutungen führt. Dann beginnt der ganze Zyklus von vorne! Es ist wie eine monatliche Tanzparty für unseren Körper! 💃🩸",
"Wann bekomme ich meine erste Periode?",
"FAQs und verbreitete Mythen",
"Die meisten Mädchen bekommen also normalerweise ihre erste Periode, wenn sie etwa 12 Jahre alt sind, aber weißt du was? Es ist total cool, wenn es zwischen 10 und 15 passiert. 🎉 Dein Körper hat einfach seinen eigenen Zeitplan und macht seine Sache.“ ! Es gibt kein festgelegtes Alter dafür, aber es gibt einige Hinweise darauf, dass es auf dem Weg sein könnte: Oft bemerken Sie etwa zwei Jahre, nachdem Ihre Brüste zu wachsen beginnen, Ihre Periode. Außerdem gibt es dieses Ding Dieser sogenannte Vaginalausfluss ähnelt Schleim, den du vielleicht in deiner Unterwäsche siehst oder fühlst. Keine Sorge, es ist alles nur dein Körper, der sich auf dieses neue Abenteuer vorbereitet! 🌟 Also, wann immer es passiert, mach einfach mit! Dein Körper weiß, was er tut. 💪",
"Wie fühlt sich die erste Periode an?",
"Menstruelle Gesundheit und psychisches Wohlbefinden",
"Hey Mädchen! Wenn du also deine Periode bekommst, ist es so, als würde dein Körper jeden Monat eine kleine Party veranstalten! 🎉 Aber hey, es ist völlig normal, wenn du dich in dieser Zeit etwas nervös fühlst.Manche Mädchen bekommen Krämpfe oder fühlen sich etwas müde, aber keine Sorge, das ist alles Teil des Pakets. Stellen Sie sich vor, Ihr Körper macht seine Sache und bereitet sich auf alle Abenteuer vor, die auf Sie zukommen! 💪 Und hey, es ist nicht alles schlecht! Vielleicht haben Sie die Möglichkeit, ein paar süße Periodenunterwäsche zu rocken oder ein paar lustige Periodenprodukte auszuprobieren! 🩲 Also, umarme den Fluss, Mädchen! Und denken Sie daran: Es gehört zum Erwachsenwerden dazu, großartig zu sein! 🌸💖",
"Menstruationshygiene und -management",
"Periodenhygiene 101: Ein Handbuch für eine saubere Königin?",
"Hygiene steht während Ihrer Periode an oberster Stelle! Beginnen Sie mit dem häufigen Wechseln von Binden, Tampons oder Tassen – den unbesungenen Helden. 🩸 Waschen Sie Ihre Hände vorher und nachher, damit Sie zum Hygiene-Superstar werden. 🧼 Entscheiden Sie sich für sanfte, parfümfreie Tücher oder Reinigungsmittel. 🌸 Halten Sie das heilige „Unterwäsche-Arsenal“ auf Lager und wechseln Sie es bei Bedarf. 💪 Nutzen Sie die Kraft des Duschens – es ist Ihr Periodenfreund. 🚿 Widerstehen Sie schließlich der Versuchung, Binden zu spülen – lassen Sie den Müll ihr endgültiges Ziel sein. 🚫 Das tun Sie Es geht nicht nur um die Aufrechterhaltung der Hygiene; Sie sind eine saubere Königin, die über Ihr Periodengebiet herrscht!",
"Pad Power: Dein Perioden-Kumpel",
"Einlagen sind wie magische Schutzschilde für Ihre Periode. 🛡️ Ziehen Sie eine aus der Verpackung, stecken Sie sie in Ihre Unterwäsche (klebrige Seite nach unten) und schon sind Sie fertig. Tauschen Sie sie alle 4–6 Stunden oder früher aus, wenn sie voll ist. ⏰ Wenn sie voll ist Es ist Zeit, sich zu trennen, es in Toilettenpapier einzuwickeln, es in den Müll (nicht in die Toilette) zu werfen und ta-da – du bist ein Perioden-Profi! 🗑️ Und denk dran, Binden gibt es in verschiedenen Größen, also wähle diejenige, die sich anfühlt Genau das Richtige für Sie. Einfach, bequem und Sie haben das Sagen! 💪🩸",
"Stain S.O.S.: Dress Edition",
"Ups, ein Periodenfleck? Kein Problem! Handeln Sie schnell: Nehmen Sie etwas kaltes Wasser und tupfen Sie den Fleck sanft ab. 💦 Wenn Sie ein Detektiv mit Rucksack sind, wirkt ein Pullover um die Taille Wunder. 🧥 Gehen Sie ins Badezimmer und verwenden Sie Seife und kaltes Wasser, um den Fleck im Ninja-Stil zu bekämpfen. 🚽 Zur Not? Entscheiden Sie sich für eine strategische Schichtung oder leihen Sie sich den Notfall-Hoodie eines Freundes. 👚 Denken Sie daran, Flecken passieren – Sie sind ein Flecken-Superheld im Entstehen! 💪🩸",
"Periodenprodukte 101: Ihr praktischer Leitfaden",
"Perioden werden mit einer Vielzahl von Produkten geliefert, die zu Ihrem Komfort passen. \n\n1. Einlagen: Als Erstes haben wir Einlagen. Diese Babys bestehen aus bequemer Baumwolle und sind in allen Formen und Größen erhältlich. Sie haben Klebestreifen Damit sie auf Ihrer Unterwäsche an Ort und Stelle bleiben. Super einfach und zuverlässig! 👍 Stecken Sie sie in Ihre Unterwäsche, um eine bequeme Schicht zu erhalten. Wechseln Sie sie nach Bedarf.\n\n2. Tampons: Diese kleinen Wunder gehen hinein und saugen den Flüssigkeitsfluss auf. Wählen Sie die Größe Das passt zu Ihrem Blutflussniveau. 🌊 Diese können eine entscheidende Veränderung sein, insbesondere für aktive Mädchen, die gerne Sport treiben oder schwimmen. Tampons sind wie kleine Wattestäbchen, die Sie in Ihre Vagina einführen. Sie werden mit praktischen Applikatoren geliefert, die Ihnen dabei helfen. Aber denken Sie daran ⏰\n\n3. Menstruationstassen: Wie ein wiederverwendbarer Superheld fangen sie den Tampon auf. Falten, einführen, fertig stundenlang haltbar. ♻️ Diese bestehen aus Silikon und sind wiederverwendbar, was ziemlich cool ist! Sie stecken sie einfach hinein und sie sammelt das Blut, bis Sie bereit sind, sie zu entleeren. Außerdem ist es umweltfreundlich! 🌱\n\n4. Periodenhöschen: Unterwäsche mit eingebauter Magie. Sie bewältigen leichte bis mäßige Strömungen ohne zusätzliche Hilfe. 👙\n\n5. Periodenscheiben: Ein bisschen wie ein Frisbee für deinen Flow. Sammeln Sie es intern und Sie können es für eine Weile vergessen. 🥏\n\nDenken Sie daran, es kommt nur darauf an, was sich für Sie richtig anfühlt. Wählen Sie Ihren Periodenpartner und schon sind Sie bereit für das monatliche Abenteuer! 🌈🩸✨\n\nSo, da haben Sie es! Experimentieren Sie ein wenig und finden Sie heraus, was sich für Sie richtig anfühlt. Deine Periode, deine Regeln! 💁‍♀️🩸",
"Physiologie verstehen",
"Periods Unveiled: Der ultimative Leitfaden für Mädchen",
"Keine Angst, Periodenkriegerin! Wenn Tante Flow sich während der Schulzeit für einen Besuch entscheidet, schmuggeln Sie einen Vorrat an Binden oder Tampons in Ihre Tasche. 🎒 Verbünden Sie sich mit einem treuen Freund – einem Periodenfreund, wenn Sie so wollen –, der Ihnen vielleicht den Rücken stärkt Vorräte. 🤝 Wenn das Unerwartete passiert, geraten Sie nicht in Panik; die meisten Schulen verfügen über diskret ausgestattete Toiletten oder eine hilfsbereite Krankenschwester. 🚽 Halten Sie für alle Fälle immer eine Geheimwaffe bereit, wie zum Beispiel einen kuscheligen Pullover um die Taille. 🧥 Und denken Sie daran, Sie Wir sind nicht allein – wir alle kennen das und es ist nur ein weiterer Tag im Leben eines Periodenprofis! 💪🩸",
"Willkommen in der Welt der Periode – ein monatliches Abenteuer! 🎉 Lernen Sie zunächst Ihre treuen Begleiter kennen: Binden, Tampons oder Menstruationstassen. 🩸 Verfolgen Sie Ihren Zyklus mit Apps oder altmodischen Kalendern; Wissen ist Macht. 📅 Tragen Sie bequeme Kleidung, Eine Wärmflasche und vielleicht etwas Schokolade während der monatlichen Fiesta. 🍫 Keine Angst vor Flecken – bekämpfen Sie sie mit kaltem Wasser und einer Superhelden-Mentalität. 💦 Chatten Sie mit vertrauenswürdigen Freunden oder Erwachsenen, wenn Sie Unterstützung brauchen. 🗣️ Denken Sie daran, die Periode gehört Ihrem Körper Art zu sagen: „Hey, ich bin großartig!“ 💁 Du hast die Kontrolle, Periodenprofi! 💪🌟",
"Dekodierung von PMS: Der monatliche Gast",
"FAQs und verbreitete Mythen",
"PMS steht für Prämenstruelles Syndrom – ein begleitender Begleiter, der vor Ihrer Periode auftritt. 🚶‍♀️ Es bringt eine Mischung aus körperlichen und emotionalen Begleiterscheinungen mit sich, wie Stimmungsschwankungen, Krämpfen und Blähungen. 😩 Denken Sie darüber nachEs ist die Art und Weise Ihres Körpers, Ihnen mitzuteilen, dass die Periodenparty bevorsteht. 🎉 Heißhunger auf Schokolade, zärtliche Gefühle und gelegentliche Superhelden-Stimmungsschwankungen können die Parade begleiten. 🍫 Mach dir keine Sorgen; es ist alles Teil des monatlichen Skripts. 📜 Gönnen Sie sich etwas Gutes, vielleicht mit einem Schokoriegel, und reiten Sie auf der PMS-Welle wie der Periodenprofi, der Sie sind! 🌊🍫🌟",
"Kann ein Mädchen schwanger werden, sobald ihre Periode beginnt?",
"Ja, ein Mädchen kann schwanger werden, sobald ihre Periode einsetzt. 🤰 Ein Mädchen kann sogar direkt vor ihrer ersten Periode schwanger werden. 🔄 Dies liegt daran, dass die Hormone eines Mädchens möglicherweise bereits aktiv sind. 💫 Die Hormone haben möglicherweise zum Eisprung geführt und der Aufbau der Gebärmutterwand. 🏗️ Wenn ein Mädchen Sex hat, kann sie schwanger werden, auch wenn sie noch nie eine Periode hatte. 🚼",
"Bewältigung von Regelschmerzen und Unterstützung",
"Krampf 101: Regelschmerzen zähmen",
"Periodenkrämpfe sind wie ein kleines Training für den Bauch – nicht die besten Gäste, oder? 💔 Bekämpfen Sie Ihren Bauch mit einer warmen Unterlage oder bei Bedarf mit Schmerzmitteln. 🔥 Trinken Sie Wasser, um hydriert zu bleiben – das ist wie Ihre Geheimwaffe. 💧 Probieren Sie es aus Einfache Übungen wie Dehnübungen oder Yoga; sie sind wie Superheldenbewegungen gegen Krämpfe. 🧘‍♀️ Suchen Sie sich einen bequemen Platz, schauen Sie sich Ihre Lieblingssendungen an und entspannen Sie sich. 📺 Denken Sie daran, Sie sind der Boss dieser Krämpfe; sie bleiben nicht bestehen für immer. 💪🩸",
"Period Sidekick 101: Ein Taschenführer",
"Freunde während ihrer Periode zu unterstützen ist ein Kinderspiel! 💨 Schritt eins: Besorgen Sie sich Schokolade, den ultimativen Trostgenuss. 🍫 Bieten Sie gemütliche Annehmlichkeiten wie ein Heizkissen und beherrschen Sie die Kunst der Deckennester. 🛌 Seien Sie der Ablenkungsguru mit Witzen oder süßen Videos . 🤣 Du bist nicht nur ein Freund; du bist der Superheld in ihrer Periodensaga! 💪🩸",
"Schulzeiten: Ein kurzer Leitfaden zum Überleben",
"Party in der ersten Periode: Ihre Kurzanleitung",
"Herzlichen Glückwunsch zum Beitritt zum Periodenclub! 🎉 Schritt eins: Keine Panik; es ist eine natürliche Superheldenfähigkeit. 💪 Suchen Sie nach Vorräten – Binden oder Tampons – und wenn Sie sich nicht sicher sind, kann ein vertrauenswürdiger Freund oder ein verständnisvoller Erwachsener Ihr Kumpel sein . 🦸 Gönnen Sie sich bequeme Stimmung mit lockerer Kleidung und vielleicht einer Wärmflasche. 🌡️ Feiern Sie diesen Übergangsritus – Sie sind offiziell ein Periodenprofi! 💫🩸",
"Das Geheimnis der Wechseljahre wird enthüllt",
"Die Wechseljahre sind wie das große Finale auf dem Weg zur Frau. 🎉 Dann beschließen die Eierstöcke, eine Pause von ihrer Eizellenproduktion einzulegen. 🥚 Die Wechseljahre treten normalerweise in den späten 40ern oder frühen 50ern auf und bringen eine Pause für die Menstruationsparty. 🎉 Verabschieden Sie sich von der Periode, aber begrüßen Sie neue Abenteuer! 👋 Neben dieser Veränderung können hormonelle Veränderungen Hitzewallungen, Stimmungsschwankungen und andere Cameo-Auftritte mit sich bringen. 🔥 Machen Sie sich keine Sorgen, es ist ein natürlicher Teil der Lebensgeschichte. 📖 Nehmen Sie es an Grace, vielleicht ein Fan von Hitzewallungen, und wisse, dass du ein neues Kapitel aufschlägst – die weise und wunderbare Welt der Postmenopause. 🚪🚶‍♀️🌅",
"Profil",
"Lieblingsblogs",
"Sprache wählen",
"Wählen Sie die Sprache aus, die Ihren Vorlieben am besten entspricht",
"Gefällt mir Videos",
"Keine Blogs gefunden",
"Registrierte Veranstaltungen",
"Erkunden Sie Ihre schriftlichen Erkenntnisse",
"Kuratieren Sie Ihre bevorzugten Lektüre",
"Bleiben Sie über Ihre Engagements auf dem Laufenden",
"Markierte Artikel",
"Greifen Sie auf Ihre markierten Lesevorgänge zu",
"Halten Sie Ihre bevorzugten Videos griffbereit",
];
