List<String> originalStrings = [
"Explorez votre cycle",
"Accédez à des ressources éducatives et à du contenu précieux pour un parcours menstruel plus sain.",
"Votre guide personnel",
"Rencontrez Paddy, votre compagnon chatbot personnel - posez des questions librement, gardez vos secrets confidentiels et obtenez des conseils personnalisés.",
"Permettre le changement grâce au don et à l'engagement",
"Soutenez des causes, partagez des histoires et connectez-vous avec des personnes partageant les mêmes idées",
"Hygiène menstruelle",
"E-mail",
"Mot de passe",
"Souviens-toi de moi",
"Mot de passe oublié?",
"Se connecter",
"Créer un compte",
"Connectez-vous avec la période",
"Rejoignez notre communauté pour un soutien et des ressources personnalisés en matière de santé menstruelle.",
"Ou connectez-vous avec",
"Sauter",
"Entrez votre email pour recevoir des instructions sur la réinitialisation de votre mot de passe et retrouver l'accès à Period.",
"Soumettre",
"E-mail de réinitialisation du mot de passe envoyé",
"La sécurité de votre compte est notre priorité! Nous vous avons envoyé un lien sécurisé pour modifier votre mot de passe en toute sécurité et protéger votre compte.",
"Fait",
"Ré-envoyer l'email",
"Prénom",
"Nom de famille",
"Nom d'utilisateur",
"Pas de téléphone.",
"Créer un compte",
"ou inscrivez-vous avec",
"Vérifiez votre adresse e-mail",
"Confirmez votre adresse e-mail pour débloquer un accès complet aux ressources sur la santé menstruelle de Period.",
"Votre adresse e-mail a été vérifiée avec succès. Profitez d'un accès complet aux ressources sur la santé menstruelle et au soutien communautaire.",
"Continuer",
"Ré-envoyer l'email",
"Tapez un message",
"Catégories",
'Organisateur',
"Campagnes",
"Événements",
"Organisations de recherche",
"Guide du débutant sur la santé menstruelle ",
'Vidéos liées',
"Derniers articles",
'Détails du cours',
'Introduction',
"Qu'est-ce que la ménopause",
"Qu'est-ce qui gêne les femmes ",
'Modifier la photo de profil',
'Informations sur le profil',
'Nom',
'Informations personnelles',
'Date de naissance',
"Compte",
'Paramètres du compte',
"Ressources mises en favoris",
"Mes dons",
"Mes blogs",
"Campagnes préférées",
"Blogs enregistrés",
"Suivez vos contributions",
"Vos expériences en un seul endroit",
"Restez connecté aux causes qui vous tiennent à cœur",
"Vos lectures préférées",
"Explorez vos trésors pédagogiques sauvegardés",
"Paramètres de l'application",
"Changer de langue",
"Adaptez votre expérience avec un changement de langue",
"Bienvenue à Période !",
"Que sont les règles ?",
"Ajouté aux blogs aimés",
"Échec de l'ajout aux blogs appréciés",
"Description",
"Aucun événement trouvé",
"Faire un don maintenant",
"En savoir plus",
"Vous y êtes!",
"Merci d'avoir participé à l'événement de don. Votre soutien fait la différence!",
"Registre",
"Télécharger le blog",
"Télécharger une image",
"Titre",
"Contenu",
"Catégorie",
"Échec du téléchargement du billet de blog",
"Télécharger le blog",
"Rechercher des blogs",
"Derniers blogs",
"Comment ça va?",
"Aujourd'hui",
"Se sentir généreux",
"Campagne introuvable",
"Événement introuvable",
"Rechercher des ressources",
"Introduction à la santé menstruelle",
"Introduction : Que sont les règles ?",
"Impact de la santé menstruelle sur la vie quotidienne",
"Hé les filles ! Alors parlons des règles, ou comme nous les appelons, des menstruations ! C'est une chose mensuelle qui nous arrive, mesdames. En gros, c'est quand du sang et des tissus sortent de notre utérus par le vagin. Cela se produit généralement quand on a 12 ans, mais bon, c'est différent pour chacun - certains peuvent commencer plus tôt, d'autres plus tard. Mais ne vous inquiétez pas, tout cela fait partie du fait de grandir et de se préparer à d'éventuelles aventures de naissance de bébé plus tard! 😊 Pendant cette période, vous pourriez ressentir toutes sortes d'émotions et peut-être un certain inconfort, mais ne vous inquiétez pas! Il existe des moyens de gérer cela, et cela ne dure généralement que quelques jours. Il est très important de connaître les règles pour pouvoir prendre soin de vous et sentez-vous à l'aise d'en discuter avec des adultes de confiance. 🌸 \n\n Maintenant, entrons dans le vif du sujet! Les règles arrivent donc parce que notre corps est super intelligent et rempli d'hormones, qui sont comme de petits messagers qui envoient des signaux. Les ovaires libèrent deux hormones spéciales appelées œstrogène et progestérone. Ces hormones font ce truc sympa en rendant la muqueuse de notre utérus toute confortable et épaisse, comme un joli lit pour un bébé potentiel. Mais s’il n’y a pas de bébé en route, cette doublure se décompose et dit au revoir, provoquant le saignement. Et puis tout le cycle recommence ! C'est comme une soirée dansante mensuelle pour notre corps ! 💃🩸",
"Quand aurai-je mes premières règles ?",
"FAQ et mythes courants",
"Donc, la plupart des filles commencent généralement à avoir leurs premières règles vers l'âge de 12 ans, mais vous savez quoi ? C'est totalement cool si cela arrive entre 10 et 15 ans. 🎉 Votre corps a juste son propre horaire, il fait son travail ! Il n'y a pas d'âge fixé pour que cela se produise, mais certains indices suggèrent que cela pourrait être en cours: par exemple, souvent, environ 2 ans après que vos seins commencent à grossir, vous remarquerez peut-être que vos règles apparaissent. appelés pertes vaginales, qui sont un peu comme du mucus, que vous pourriez voir ou sentir dans vos sous-vêtements. Ne vous inquiétez pas, c'est simplement votre corps qui se prépare pour cette nouvelle aventure ! 🌟 Alors, chaque fois que cela arrive, faites avec ! Votre corps sait ce qu'il fait. 💪",
'À quoi ressemble la première période ?',
"Santé menstruelle et bien-être mental",
"Hé ma fille ! Alors, quand tu as tes règles, c'est comme si ton corps organisait une petite fête tous les mois ! 🎉 Mais bon, c'est tout à fait normal si tu te sens un peu bizarre pendant cette période. Certaines filles ont des crampes ou se sentent un peufatigué, mais ne vous inquiétez pas, tout cela fait partie du package. Considérez-le comme votre corps faisant son travail, se préparant à toutes les aventures qui vous attendent! 💪 Et bon, tout n'est pas mauvais ! Vous pourriez avoir l’occasion de porter de jolis sous-vêtements menstruels ou d’essayer des produits menstruels amusants! 🩲 Alors, adopte le flow, ma fille! Et rappelez-vous, tout cela fait partie du fait de grandir et d'être génial! 🌸💖",
"Hygiène et gestion menstruelles",
"Hygiène périodique 101:un manuel pour une reine propre?",
"L'hygiène règne en maître pendant vos règles ! Commencez par des changements fréquents de serviettes, tampons ou cups, les héros méconnus. 🩸 Lavez-vous les mains avant et après, ce qui fait de vous la superstar de l'hygiène. 🧼 Optez pour des lingettes ou des nettoyants doux et sans parfum. 🌸 Gardez votre arsenal de sous-vêtements  sacré en stock et changez-le si nécessaire. 💪 Profitez du pouvoir des douches – ce sont vos amies menstruelles. 🚿 Enfin, évitez la tentation de jeter les serviettes hygiéniques – laissez les poubelles être leur destination finale. 🚫 Vous êtes pas seulement le maintien de l'hygiène; vous êtes une reine de la propreté qui dirige votre domaine menstruel!",
"Pad Power: votre copain de règles",
"Les serviettes sont comme des boucliers magiques pour vos règles. 🛡️ Retirez-en une de son emballage, mettez-la dans vos sous-vêtements (côté collant vers le bas) et le tour est joué. Remplacez-la toutes les 4 à 6 heures ou plus tôt si elle est pleine. ⏰ Quand c'est le cas. Il est temps de se séparer, enveloppez-la dans du papier toilette, jetez-la à la poubelle (pas dans les toilettes), et ta-da – vous êtes une pro des règles! 🗑️ Et rappelez-vous, les serviettes hygiéniques sont disponibles en différentes tailles, alors choisissez celle qui vous convient. juste ce qu'il vous faut. Facile, confortable et vous êtes aux commandes! 💪🩸",
"Stain S.O.S.: Édition Robe",
"Oups, une tache de règles ? Pas grave ! Agissez vite : prenez un peu d'eau froide et épongez délicatement la tache. 💦 Si vous êtes un détective avec un sac à dos, un pull autour de la taille fait des merveilles. 🧥 Allez aux toilettes, utilisez du savon "
"Produits périodiques 101: votre guide pratique",
"Les règles sont accompagnées d'une variété de produits adaptés à votre confort. \n\n1. Serviettes hygiéniques: tout d'abord, nous avons des serviettes hygiéniques. Ces bébés sont faits de coton confortable et sont disponibles dans toutes les formes et tailles. Ils ont des bandes collantes pour les maintenir en place sur vos sous-vêtements. Super simple et fiable! 👍 Collez-les dans vos sous-vêtements pour une couche confortable. Changez-les si nécessaire.\n\n2. Tampons: Ces petites merveilles se glissent à l'intérieur et absorbent le flux. Choisissez la taille qui correspond à votre niveau de débit. 🌊 Ceux-ci peuvent changer la donne, en particulier pour les filles actives qui font du sport ou de la natation. Les tampons sont comme de petits tampons de coton que vous insérez dans votre vagin. Ils sont livrés avec des applicateurs pratiques pour vous aider. N'oubliez pas, cependant , ne laissez jamais un tampon pendant plus de 8 heures pour éviter une infection rare mais grave appelée syndrome de choc toxique. ⏰\n\n3. Coupes menstruelles: comme un super-héros réutilisable, elles collectent le flux. Pliez, insérez et vous êtes bon pendant des heures. ♻️ Ils sont fabriqués en silicone et sont réutilisables, ce qui est plutôt cool! Il vous suffit de l'insérer et il recueille le sang jusqu'à ce que vous soyez prêt à le vider. En plus, c'est écologique ! 🌱\n\n4. Culotte menstruelle:sous-vêtements dotés d'une magie intégrée. Ils gèrent les flux légers à modérés sans aucune aide supplémentaire. 👙\n\n5. Disques périodiques : Un peu comme un frisbee pour votre flow. Collectez-le en interne et vous pourrez l'oublier pendant un moment. 🥏\n\nN'oubliez pas que tout dépend de ce qui vous convient. Choisissez votre partenaire menstruel et vous êtes prêt pour l'aventure mensuelle! 🌈🩸✨\n\nEt voilà ! Expérimentez un peu et trouvez ce qui vous convient. Vos règles, vos règles ! 💁‍♀️🩸",
"Comprendre la physiologie",
"Périodes dévoilées: le guide ultime pour les filles",
"N'ayez crainte, guerrière des règles! Si tante Flow décide de vous rendre visite pendant les heures d'école, glissez une réserve de serviettes ou de tampons dans votre sac. 🎒 Faites équipe avec un ami de confiance - un copain de règles, si vous préférez - qui pourrait vous soutenir. fournitures. 🤝 Si un imprévu survient, ne paniquez pas; la plupart des écoles disposent de toilettes discrètement approvisionnées ou d'une infirmière serviable. 🚽 Ayez toujours une arme secrète, comme un pull douillet noué autour de votre taille, juste au cas où. 🧥 Et rappelez-vous, vous Nous ne sommes pas seuls – nous sommes tous passés par là, et c'est juste un autre jour dans la vie d'une pro des règles! 💪🩸",
"Bienvenue dans le monde des règles – une aventure mensuelle! 🎉 Tout d'abord, rencontrez vos fidèles compagnons: serviettes, tampons ou coupes menstruelles. 🩸 Suivez votre cycle avec des applications ou des calendriers à l'ancienne; la connaissance, c'est le pouvoir. 📅 Adoptez des vêtements confortables, une bouillotte et peut-être du chocolat pendant la fête mensuelle. 🍫 Ne craignez pas les taches – attaquez-les avec de l'eau froide et un état d'esprit de super-héros. 💦 Discutez avec des amis ou des adultes de confiance si vous avez besoin de soutien. 🗣️ N'oubliez pas que les règles appartiennent à votre corps. façon de dire : Hé, je suis incroyable ! 💁 Tu as le contrôle, pro des règles ! 💪🌟",
"Décoder les PMS : L'invité du mois",
"FAQ et mythes courants",
"PMS signifie Premenstrual Syndrome – un compagnon qui vous accompagne avant vos règles. 🚶‍♀️ Il apporte un mélange d'acolytes physiques et émotionnels, comme des sautes d'humeur, des crampes et des ballonnements. 😩 Considérez-le comme la façon dont votre corps donne toiun avertissement que la fête d'époque est en route. 🎉 Des envies de chocolat, des sentiments tendres et des sautes d'humeur occasionnelles de super-héros peuvent rejoindre le défilé. 🍫 Ne vous inquiétez pas ; tout cela fait partie du script mensuel. 📜 Faites-vous plaisir, peut-être avec une barre de chocolat, et surfez sur la vague du SPM comme la pro des règles que vous êtes ! 🌊🍫🌟",
"Une fille peut-elle tomber enceinte dès le début de ses règles ?",
"Oui, une fille peut tomber enceinte dès le début de ses règles. 🤰 Une fille peut même tomber enceinte juste avant ses toutes premières règles. 🔄 C'est parce que les hormones d'une fille peuvent déjà être actives. 💫 Les hormones peuvent avoir conduit à l'ovulation et la construction de la paroi utérine. 🏗️ Si une fille a des relations sexuelles, elle peut tomber enceinte, même si elle n'a jamais eu de règles. 🚼",
"Gérer la douleur et le soutien menstruels ",
"Cramp 101:Apprivoiser les douleurs menstruelles",
"Les crampes menstruelles sont comme de petits exercices pour votre ventre – pas les meilleurs invités, n'est-ce pas ? 💔 Combattez avec une compresse chaude sur votre ventre ou des analgésiques si nécessaire. 🔥 Buvez de l'eau pour rester hydraté – c'est comme votre arme secrète. 💧 Essayez des exercices faciles comme des étirements ou du yoga; ce sont comme des mouvements de super-héros contre les crampes. 🧘‍♀️ Trouvez un endroit confortable, regardez vos émissions préférées et détendez-vous. 📺 N'oubliez pas que vous êtes le patron de ces crampes; elles ne resteront pas là pour toujours. 💪🩸",
"Période Sidekick 101: Un guide de poche",
" Soutenir ses amies pendant leurs règles est un jeu d'enfant! 💨 Première étape: faites le plein de chocolat, le réconfort ultime. 🍫 Offrez un confort douillet comme un coussin chauffant et maîtrisez l'art des nids de couverture. 🛌 Soyez le gourou de la distraction avec des blagues ou de jolies vidéos . 🤣 Tu n'es pas qu'un ami, tu es le super-héros de leur saga menstruelle! 💪🩸",
"Les règles à l'école: un guide de survie rapide",
"Fête des premières règles: votre guide rapide",
"Félicitations pour avoir rejoint le club menstruel! 🎉 Première étape: ne paniquez pas; c'est une compétence naturelle de super-héros. 💪 Vérifiez les fournitures - serviettes ou tampons - et si vous n'êtes pas sûr, un ami de confiance ou un adulte compréhensif peut être votre acolyte . 🦸 Adoptez une ambiance confortable avec des vêtements amples et peut-être une bouillotte. 🌡️ Célébrez ce rite de passage – vous êtes officiellement un pro des règles! 💫🩸",
"Le mystère de la ménopause dévoilé",
"La ménopause est comme la grande finale du voyage vers la féminité. 🎉 C'est lorsque les ovaires décident de faire une pause dans leur activité de production d'ovules. 🥚 Survenant généralement à la fin des années 40 ou au début des années 50, la ménopause apporte une pause dans la fête menstruelle. 🎉 Dites adieu aux règles, mais bonjour aux nouvelles aventures! 👋 Parallèlement à ce changement, les changements hormonaux peuvent entraîner des bouffées de chaleur, des sautes d'humeur et d'autres apparitions. 🔥 Ne vous inquiétez pas; cela fait naturellement partie de l'intrigue de la vie. 📖 Acceptez-le avec grâce, peut-être fan des bouffées de chaleur, et sachez que vous entrez dans un nouveau chapitre – le monde sage et merveilleux de l'après-ménopause. 🚪🚶‍♀️🌅",
"Profil",
"Blogs préférés",
"Choisissez la langue",
"Sélectionnez la langue qui correspond le mieux à vos préférences",
"Vidéos aimées",
"Aucun blog trouvé",
"Événements enregistrés",
"Explorez vos idées écrites",
"Organisez vos lectures préférées",
"Restez informé de vos engagements",
"Articles favoris",
"Accédez à vos lectures favorites",
"Gardez vos vidéos préférées à portée de main",
];
